language: r

sudo: required

apt_packages:
  - texlive
  - ghostscript
  - texlive-fonts-extra
  - texinfo

script:
  - bash build.sh

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e "covr::coveralls()"
