context("NA subjects")

## testthat there is no warning generated by a piece of code.
gives_no_warning <- function(){
  function(expr) {
    warnings <- evaluate_promise(expr)$warnings
    s <- ifelse(length(warnings)==1, "", "s")
    expectation(
      length(warnings) == 0,
      paste0("created ", length(warnings),
             " warning", s, ": ",
             paste(warnings, collapse=", ")),
      "no warnings given"
    )
  }
}
expect_no_warning <- function(object, ..., info=NULL, label=NULL){
  if (is.null(label)) {
    label <- testthat:::find_expr("object")
  }
  expect_that(object, gives_no_warning(), info=info, label=label)
}

N <- 1e5
subject.vec <- c("this will match", rep(NA, N))
pattern <- paste0("(?<name>ill)(?<rest>.*)")

test_that("NA subjects do not cause warnings", {
  ## Sometimes the C code underly regexpr will return large ints in
  ## capture start/length for subjects with missing values, and in
  ## that case we were seeing the warning "NAs introduced by coercion
  ## to integer range." but sometimes (randomly) it did not cause a
  ## warning.
  expect_no_warning({
    computed.mat <- str_match_named(subject.vec, pattern)
  })
  expected.mat <- matrix(
    c(" match", rep(NA, N)),
    dimnames=list(c("ill", rep(NA, N)), "rest"))
  expect_identical(computed.mat, expected.mat)
})
